### ISSUE TITLE
File / Folder Details in Repository - URGENT

### ISSUE THREAD

**Issue by mbsarino** [projectfork/Projectfork#1465]
I have a problem with the repository.  The file / folder information reflects the original author/uploader of the document and not the user that modified/uploaded the latest version.  

What do I need to change to reflect the name of the uploading / modifying user?

Any immediate help is appreciated as my intranet site is live and the modification needs to be done immediately.

@angek 
@eaxs

**Comment by mbsarino** [comment]
Hi @kyleledbetter :

I have edited the following files, replaccing  <?php echo $this->escape($item->author_name); ?> with  <?php echo $this->escape($item->editor_name); ?> and I still get the following screenshot when I edit a file.  Please note, the user modifying the file is not a Super User:

components/com_pfrepo/site/views/filerevisions/tmpl/default.php

![capture - pfrepo5](https://cloud.githubusercontent.com/assets/7676572/5609437/28518882-94d3-11e4-9670-8a8d15ccd836.JPG)

**Comment by mbsarino** [comment]
@kyleledbetter 

Any ideas as to what else is needed to get the "Editor" name on the file list?  With the overrides, even the Author Name doesn't show up in the directories list as shown in this image.

![capture - pfrepo2](https://cloud.githubusercontent.com/assets/7676572/5625592/b2d4946c-95b0-11e4-9f05-0a20524ae5f0.JPG)

I am also getting a "/" before each file.  Why is that?

**Comment by kyleledbetter** [comment]
Hmmm for your previous screenshot I had actually told you the wrong file to override, but in looking at it, that file already uses modified, not created for the "Modified by" field (it's here https://github.com/projectfork/Projectfork/blob/dev/source/components/com_pfrepo/site/views/fileform/tmpl/edit.php#L122) are you sure the Super User wasn't the last to modify?

For the last screenshot, the / forward slash is the directory you're in, which is the root directory. If you add a folder you'll get something like "/example" instead of "/"
