### ISSUE TITLE
REQ: Hours instead of minutes

### ISSUE THREAD

**Issue by rbrekken** [projectfork/Projectfork#1517]
What about an option to choose between minutes and hours for time tracking? Specifying 4,75 hours in minutes is quite awkward (4*60+45 = 240+45 = 285).

**Comment by angek** [comment]
I was always under the impression that you could enter it like "5 hours" and it would work. Let me check the code and I'll get back to you.

**Comment by angek** [comment]
OK had a look at the code and it does the following:
1. it checks to see if what you entered is numeric. If it is then it automatically assumes you've entered the time in minutes (as expected)
2. for all non numeric time entries it passes the value to strtotime() which will either accept the English textual datetime and return a Unix timestamp or return false because the English textual datetime is not valid. Valid formats can be found at http://php.net/manual/en/datetime.formats.php

so in your case entering "4 hours 45 mins"  to represent 4.75 hours would work.
