### ISSUE TITLE
Error when trying to set active project via code

### ISSUE THREAD

**Issue by HelgeSverre** [projectfork/Projectfork#1586]
## My Code:
```php
jimport('projectfork.library');

// Get the id for the projectname
$projectId = self::getProjectName($attendance->checkinlocation);

// Set the active project as the one selected in com_intranet
PFApplicationHelper::setActiveProject($projectId);
```

The code above lives inside of a ```public static function``` which is accessed via Joomlas AJAX Interface (com_ajax).

Here is the error I get when executing the code above:

## Error: 
```
Fatal error: Call to a member function setActive() on a non-object in /var/www/websys/www/hs/libraries/projectfork/application/helper.php on line 214
```

Is there anything I have misunderstood about the usage of ```setActiveProject()```, does it need to be called from within a non-static class?

**Comment by eaxs** [comment]
If I remember correctly `jimport('projectfork.library');` only loads the libary itself, but not any other dependencies. As the method `setActiveProject` requires the project model, it fails if the class is not registered.

Instead of writing `jimport('projectfork.library');`, you can write `jimport('projectfork.framework');` which registers pretty much everything, including language files. But it's slower.

The third way would be write:
```php
jimport('projectfork.library');
JModelLegacy::addIncludePath(JPATH_ADMINISTRATOR . '/components/com_pfprojects/models',  'PFprojectsModel');
```

This will register the libary classes and the project model.

**Comment by HelgeSverre** [comment]
Thank you Tobias, this solution worked for me: 
```php
jimport('projectfork.framework');
```

Here, have an internet cookie * gives cookie *

**Comment by eaxs** [comment]
Thanks :)
