### ISSUE TITLE
Plugin JS Projects  dont work

### ISSUE THREAD

**Issue by hermanvz** [projectfork/Projectfork#1681]
Hello all, I have joomla 3.4.5 and joomsocial 4.0.7 but the plugin JS Projects dont work, I enable from plugin manager but this plugin I cant make to show in the profile JS.
Some one can helpme, this configuration should work?
Thanks.

**Comment by angek** [comment]
Hey @hermanvz, from what I can tell the JomSocial PF plugin was initially written for JomSocial 3. I may be wrong, but it doesnt look like it has been updated since then so it may be an incompatibility issue with JomSocial 4. From what I can tell there have been a lot of changes to JomSocial.

I don't own a copy of JomSocial so am unable to give you any more advice. I wouldn't mind discussing this further with you if you want. You can email me at angek@angekdesign.com.au

**Comment by eaxs** [comment]
The plugin works just fine. Once you've enabled it in the backend, switch to the frontend and go to your Jomsocial profile. From there, use the toolbar at the top: Profile > Customize My Page.

Then click on a slot and select the Projectfork plugin.
