### ISSUE TITLE
Character Length of Hourly Rate

### ISSUE THREAD

**Issue by febyferdinan** [projectfork/Projectfork#1734]
pls help me, how to change character length of hourly rate? because I need to put the rate more than 4 characters.
![hourlyrate](https://cloud.githubusercontent.com/assets/11747941/14229264/b26dd8ae-f959-11e5-85c9-1bb83ecd58e3.png)

**Comment by angek** [comment]
@febyferdinan I think you've stumbled on a bug.
Let me explain.....
if you look at the structure of the #__pf_tasks table you will notice that the rate is a DECIMAL(5,2) datatype. 
![ratedb](https://cloud.githubusercontent.com/assets/1072484/14230200/d666a9b6-f990-11e5-85fa-6962b42b2d77.png)
This means that it will accept a total of 5 digits (3 digits before the decimal point and 2 digits after) and because it is not unsigned the range of values that this field will hold is: -999.99 to 999.99

On the other hand if you look at the field type itself ( `/administrator/components/com_pftasks/models/forms/task.xml` ) you will notice that is it a custom defined field type (money) 
![moneyxml](https://cloud.githubusercontent.com/assets/1072484/14230199/ab91f9ca-f990-11e5-9e09-ecb5f1e46186.png)

which is defined in `/libraries/projectfork/form/fields/money.php`
The `JFormFieldMoney` class' `getInput()` method sets a default maxlength attribute of 4 characters.

![maxlength](https://cloud.githubusercontent.com/assets/1072484/14230242/e7211dbc-f991-11e5-95d7-db2bda4ec985.png)

which is then used in both the `getAdminHTML()` and `getSiteHTML()` method to limit the number of characters that can be entered into the "dollar" field for rate.

![max_length_html](https://cloud.githubusercontent.com/assets/1072484/14230295/0c7636b8-f994-11e5-93b2-7c9eff1a3fef.png)

To allow 4 digits in the "dollar" part of the rate field would require the rate db column to be set to a DECIMAL(6,2) datatype.

So to answer your question, you would first need to decide how many total digits you need to store for the rate and alter the #__pf_tasks' rate column's DECIMAL(X,2) datatype accordingly.

You would then need to alter the `/libraries/projectfork/form/fields/money.php` file to allow a maxlength attribute of (X-2).

Let's assume you need to store rates with a total length of 10 digits (which includes the 2 decimal places). You would alter the rate column's datatype to DECIMAL(10,2) and then set the maxlength to 8.

I hope I haven't confused you too much :)

**Comment by febyferdinan** [comment]
@angek absolutely clear sir, thanks for your help :)
